[package]
name = "alloc"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true, features = ["alloc"] } 

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils", "alloc"]}

[features]
testutils = ["soroban-sdk/testutils"]

